version: "3.3"

# networks:
#   memento-studio-net:
#     external: false

services:
  go-server:
    container_name: go-server
    build: .
    environment:
      - MONGO_HOSTNAME=localhost
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=PI-UFES-2022
    ports:
      - "8080:8080"
    network_mode: "host"
    # networks:
      # - memento-studio-net

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PI-UFES-2022
    ports:
      - "27017:27017"
    network_mode: "host"
    # networks:
      # - memento-studio-net
    volumes:
      - ./database-data:/data/db
