version: "3.3"

services:
  go-server:
    container_name: go-server
    build: .
    ports:
      - "8080:8080"
    network_mode: "host"

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PI-UFES-2022
    ports:
      - "27017:27017"
    network_mode: "host"
    volumes:
      - ./database-data:/data/db
