version: "3.3"

services:
  go-server:
    container_name: go-server
    build: .
    environment:
      - MONGO_HOSTNAME=localhost
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=PI-UFES-2022
      - IMAGES_FILE_PATH=public/
      - BASE_ROUTE=https://5afe-131-255-21-116.sa.ngrok.io/
    network_mode: "host"
    volumes:
      - ./public:/app/public:consistent

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PI-UFES-2022
    network_mode: "host"
    volumes:
      - ./database-data:/data/db
